[package]
name = "catts_engine"
version = "0.0.1"
edition = "2021"
authors = ["Kristofer Lund <kristofer@kristoferlund.se>"]
description = ""
license = "MIT"
homepage = "https://github.com/c-atts"
repository = "https://github.com/c-atts"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.10"
ic-cdk = "0.15.0"
serde = "1.0.193"
serde_json = "1.0.108"
ic-stable-structures = "0.6.5"
serde_bytes = "0.11"
blake2 = "0.10.6"
ethers-core = "2.0.14"
ic-cdk-timers = "0.9.0"
ic-wasi-polyfill = "0.5.0"
regex = "1.10.4"
futures = "0.3"
lazy_static = "1.4.0"
thiserror = "1.0.59"
bincode = "1.3.3"
javy = "2.2.0"
validator = "0.18.1"
validator_derive = "0.18.1"
anyhow = "1.0.86"
json-patch = "2.0.0"

[build-dependencies]
ic-cdk-bindgen = "0.1.3"
dotenv = "0.15.0"
