[package]
name = "catts_engine"
version = "0.0.1"
edition = "2021"
authors = ["Kristofer Lund <kristofer@kristoferlund.se>"]
description = ""
license = "MIT"
homepage = "https://github.com/c-atts"
repository = "https://github.com/c-atts"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
asset_util = { git = "https://github.com/kristoferlund/internet-identity.git" }
bincode = "1.3.3"
blake2 = "0.10.6"
candid = "0.10.10"
ethers-core = "2.0.14"
futures = "0.3"
handlebars = "6.0.0"
ic-canister-sig-creation = "1.1"
ic-cdk = "0.15.0"
ic-cdk-timers = "0.9.0"
ic-certification = "2.6.0"
ic-stable-structures = "0.6.5"
ic-wasi-polyfill = "0.5.0"
include_dir = "0.7.4"
javy = "2.2.0"
json-patch = "2.0.0"
lazy_static = "1.4.0"
regex = "1.10.4"
resvg = "0.43.0"
serde = "1.0.193"
serde_bytes = "0.11"
serde_json = "1.0.108"
thiserror = "1.0.59"
url = "2.5.2"
validator = "0.18.1"
validator_derive = "0.18.1"


[build-dependencies]
ic-cdk-bindgen = "0.1.3"
dotenv = "0.15.0"
